### ISSUE TITLE
How to install libnss_tacplus.so.2?

### ISSUE THREAD

**Issue by friofry** [benschumacher/nss_tacplus#1]
Hi,
It's not quite clear which step of tutorial connects libnss_tacplus.so.2 with nsswitch.conf 
("Using TACACS+ NSS module"). 

It looks like that I should add to /etc/nsswitch.conf something like:
passwd: tacplus compat
and install libnss_tacplus.so.2 somewhere.

**Comment by friofry** [comment]
I've prepared spec file for nss_tacplus, please take a look on pull request. https://github.com/benschumacher/nss_tacplus/pull/2

**Comment by benschumacher** [comment]
Closed by #2.
