### ISSUE TITLE
source compiling error in RHEL6.6

### ISSUE THREAD

**Issue by manojknair85** [benschumacher/nss_tacplus#5]
Getting below error and exit while compiling the code in rhel6.6 OS. Ia that bug or dependency issue.  

gcc  -D_FORTIFY_SOURCE=2 -fstack-protector -std=gnu99 -Werror -Wall -ggdb -fPIC -I/usr/local/lib -c -o src/nss_tacplus.o src/nss_tacplus.c
src/nss_tacplus.c: In function ‘_nss_tacplus_getpwnam_r’:
src/nss_tacplus.c:674: error: too few arguments to function ‘tac_connect_single’
make: *** [src/nss_tacplus.o] Error 1

**Comment by thecreed** [comment]
its not compatible with latest build of pam_tacplus,

fix:
in src/nss_tacplus.c

change to:
tac_fd = tac_connect_single(server, G_tacplus_conf.secret, NULL, **60**);

**Comment by benschumacher** [comment]
Closed by #2.
